import type { Config } from "tailwindcss";

export default {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            spacing: {
                0: "0px",
                2: "0.125rem",
                4: "0.25rem",
                6: "0.375rem",
                8: "0.5rem",
                12: "0.75rem",
                16: "1rem",
                20: "1.25rem",
                24: "1.5rem",
                32: "2rem",
                40: "2.5rem",
                48: "3rem",
                64: "4rem",
                72: "4.5rem",
                80: "5rem",
                96: "6rem",
                120: "7.5rem",
                160: "10rem",
                200: "12.5rem",
                240: "15rem",
                280: "17.5rem",
                320: "20rem",
                400: "25rem",
            },
            fontSize: {
                xxs: "0.25rem",
                xs: "0.5rem",
                sm: "0.75rem",
                md: "1rem",
                lg: "1.25rem",
                xl: "1.5rem",
                "2xl": "2rem",
                "3xl": "2.5rem",
                "4xl": "3rem",
                "5xl": "4rem",
                0: "0rem",
                2: "0.125rem",
                4: "0.25rem",
                6: "0.375rem",
                8: "0.5rem",
                12: "0.75rem",
                16: "1rem",
                20: "1.25rem",
                24: "1.5rem",
                32: "2rem",
                40: "2.5rem",
                48: "3rem",
                64: "4rem",
                72: "4.5rem",
                80: "5rem",
                96: "6rem",
                120: "7.5rem",
                160: "10rem",
                200: "12.5rem",
                240: "15rem",
                280: "17.5rem",
                320: "20rem",
                400: "25rem",
            },
            fontFamily: {
                sans: "Roboto",
            },
            fontWeight: {
                thin: "100",
                light: "300",
                regular: "400",
                medium: "500",
                bold: "700",
                extraBold: "900",
            },
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
            },
            boxShadow: {
                neumorph: "12px 12px 24px #cfc6bb, -12px -12px 24px #fffffd",
            },
        },
    },
    plugins: [],
} satisfies Config;
