export const loremIpsum: string[] = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mi ex, tempor sed viverra vel, varius ut massa. Morbi id tellus ac risus pharetra pulvinar sed facilisis dui. Nulla pellentesque aliquet justo at mollis. Morbi pretium quis turpis eget rutrum. Praesent sem nibh, fermentum et gravida nec, dignissim eget ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sed tortor nisi. In sagittis erat quis dolor gravida aliquet at ut dui. Aenean et metus feugiat, posuere velit sit amet, congue arcu. Morbi ut ipsum enim. Maecenas maximus ex nec odio convallis lobortis.",
    "Pellentesque eu augue nisi. Nam tortor augue, dictum non purus eget, sollicitudin hendrerit risus. Pellentesque nec nibh est. Praesent ut lorem semper, efficitur erat vitae, consequat dui. In vitae urna lacus. Proin vitae nunc vestibulum, accumsan metus quis, laoreet arcu. Fusce auctor vulputate velit sed posuere. Morbi finibus tempus sapien. Mauris sit amet nisl lorem. Curabitur sagittis, erat a tincidunt tincidunt, enim massa pharetra justo, sed commodo neque turpis cursus quam. Aliquam dignissim, turpis eget faucibus bibendum, diam nulla lacinia sem, eget consequat dolor massa egestas magna.",
    "Nulla fringilla eleifend vestibulum. Curabitur dapibus tortor non ligula blandit, in bibendum neque pretium. Proin convallis, libero at mattis dictum, justo leo iaculis purus, vitae mollis sem mauris ac sem. Suspendisse ex magna, ullamcorper nec urna sit amet, posuere fringilla dolor. Ut quis risus a libero tempor hendrerit ut ultrices lectus. Donec dignissim ante nulla, a egestas lorem aliquet quis. In finibus magna et euismod lobortis. Morbi interdum consequat suscipit. Phasellus sagittis magna nibh, sed tristique ipsum venenatis et. Donec non fermentum felis. Vestibulum id justo consequat, ultricies lectus ac, faucibus diam. Suspendisse vehicula, justo a scelerisque tincidunt, enim sem ultrices nisi, quis eleifend ex urna ac urna. Cras semper tristique urna ut dictum. Mauris tristique magna sed tellus malesuada cursus.",
    "Mauris viverra porta laoreet. Vestibulum eu massa nec justo iaculis porttitor quis sed magna. Donec pellentesque dui nec libero fringilla, ut imperdiet orci tincidunt. Aliquam erat volutpat. Etiam et tristique arcu. Donec eget convallis mauris. Vivamus ac dignissim leo. Sed sit amet faucibus massa. Aenean vel tellus tempor, malesuada sapien finibus, tincidunt nisi. Curabitur vitae ullamcorper nibh. Proin nec libero sit amet nulla semper feugiat. Sed quis ipsum sed augue mattis lobortis.",
    "Integer aliquam fringilla magna non lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. In vel sem sed nunc vulputate rutrum. Phasellus rhoncus nisi quis sem gravida, nec iaculis enim pretium. Curabitur venenatis nec neque vitae laoreet. Duis nec commodo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a posuere libero. Curabitur semper orci vel tempus tincidunt. Nulla tempor dictum mi a aliquet. Pellentesque a felis dui. Duis finibus commodo pharetra.",
    "Suspendisse eu aliquet ipsum, in egestas sem. Nulla iaculis porta lectus a consequat. Ut risus libero, ornare id mi vitae, maximus finibus sem. Sed pulvinar ligula nec porttitor pellentesque. Quisque eget aliquet massa. Donec rhoncus sagittis arcu ut dignissim. Sed cursus, nisi in malesuada posuere, arcu ligula vulputate odio, eget blandit tortor ligula vitae eros. Sed vulputate est sit amet neque sollicitudin condimentum. Vestibulum aliquet scelerisque nulla, non rutrum enim efficitur vitae. Nunc congue lacinia ante, eget iaculis odio. Donec nisl enim, luctus at dolor at, tempor feugiat sapien. Sed a ex viverra, egestas mauris vitae, elementum orci. Pellentesque ullamcorper vehicula tellus eget pulvinar. Mauris at maximus massa.",
    "Fusce sagittis dui urna, sed elementum ante faucibus non. Sed at quam sit amet nulla ultricies mattis ac et velit. Morbi tincidunt, orci in pellentesque ultrices, lectus dolor tristique tortor, eu facilisis eros libero sed nunc. Phasellus dictum non ligula sed laoreet. Donec sed eros lorem. Integer at orci quis velit sodales dictum. Nunc nec laoreet velit. Sed nec auctor elit. Vestibulum ac enim metus. Aenean quam ante, euismod convallis cursus ac, fermentum et tortor.",
];
